<?php

namespace Gloubster\Worker;

require_once dirname(__FILE__) . '/../../../../src/Gloubster/Worker/RunWorkers.php';

/**
 * Test class for RunWorkers.
 * Generated by PHPUnit on 2012-07-04 at 16:13:20.
 */
class RunWorkersTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RunWorkers
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
//        $this->object = new RunWorkers;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Gloubster\Worker\RunWorkers::execute
     * @todo Implement testExecute().
     */
    public function testExecute()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}

?>
