language: php

before_script:
  - sudo apt-get install -y php5-gd redis-server libcloog-ppl0 libcloog-ppl-dev libboost-all-dev libevent-core-2.0-5 libevent-dev libevent-extra-2.0-5 libevent-openssl-2.0-5 libevent-pthreads-2.0-5
  - wget https://launchpad.net/gearmand/trunk/0.33/+download/gearmand-0.33.tar.gz
  - tar xzvf gearmand-0.33.tar.gz
  - sh -c "cd gearmand-0.33 && ./configure && make -j && sudo make install"
  - wget http://pecl.php.net/get/gearman-1.0.2.tgz
  - tar xzvf gearman-1.0.2.tgz
  - sh -c "cd gearman-1.0.2 && phpize && ./configure && make && sudo make install"
  - echo "extension=gearman.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - git clone https://github.com/nicolasff/phpredis.git
  - sh -c "cd phpredis && phpize && ./configure && make && sudo make install"
  - echo "extension=redis.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

php:
  - 5.3
  - 5.4

script:
  - phpunit
