language: php

services:
  - rabbitmq

before_script:
  - sudo rabbitmq-plugins enable rabbitmq_management
  - sudo rabbitmq-plugins enable rabbitmq_stomp
  - wget http://guest:guest@localhost:55672/cli/rabbitmqadmin
  - chmod +x rabbitmqadmin
  - ./rabbitmqadmin declare queue name=phrasea.worker.test-queue durable=true
  - ./rabbitmqadmin declare exchange name=phrasea.subdef.dispatcher type=fanout
  - ./rabbitmqadmin declare exchange name=phrasea.monitor type=fanout
  - sudo apt-get install ffmpeg
  - composer install --dev

php:
  - 5.3
  - 5.4

script:
  - phpunit
