language: php

before_script:
  - sudo apt-get install -y redis-server
  - git clone https://github.com/nicolasff/phpredis.git
  - sh -c "cd phpredis && phpize && ./configure && make && sudo make install"
  - echo "extension=redis.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - wget http://pecl.php.net/get/gearman-1.0.2.tgz
  - tar xzvf http://pecl.php.net/get/gearman-1.0.2.tgz
  - sh -c "cd gearman-1.0.2 && phpize && ./configure && make && sudo make install"
  - echo "extension=gearman.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

php:
  - 5.3
  - 5.4

script:
  - phpunit
